# what is Numpy?

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# Why use Numpy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
import numpy as np

#### Arrays

In [ ]:
#.array()
ls = [1,2,3,4]
array = np.array(ls)
print(ls)
print("---------------------------\n")
print(array)

[1, 2, 3, 4]
---------------------------

[1 2 3 4]


In [ ]:
ls2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr2 = np.array(ls2)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# accessing element in an array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3[0, 1, 2])

6


In [ ]:
#print the last element of the second row
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Iterating over elements

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr: #rows x= [1,2,3]
    for y in x: #cols y = 1, = 2, =3
        print(y)

1
2
3
4
5
6


In [ ]:
#using diter
for x in np.nditer(arr):
    print(x)
print("------------------------\n")

#skipping 1 element
for x in np.nditer(arr[:, ::2]):
    print(x)

1
2
3
4
5
6
------------------------

1
3
4
6


### Joining Numpy arrays

In [ ]:
#concatenate()
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#a long rows (hstack())
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#along cols (vstack())
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Slicing arrays

In [ ]:
#find the elements from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4])

[2 3 4]


In [ ]:
#Negative slicing
# slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
# step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-6:-1:2])

[2 4 6]


In [ ]:
#reversed array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::-1])

[7 6 5 4 3 2 1]


In [ ]:
#return every other element from the entire array (all except 3)
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
# 2D slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


###Boolean array indexing:
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example

In [ ]:
my_arr = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (my_arr > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(my_arr[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(my_arr[my_arr > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Splitting NumPy Arrays


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr[0])
print(newarr[1])



[1 2 3]
[4 5 6]


In [ ]:
#Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### arange

In [ ]:
#.arange() ----> returns integers within a range of numbers
#arange = np.arange(1,15)
arange = np.arange(1,15,3) #-----> (_start,_end,_stepsize)
print(arange)

[ 1  4  7 10 13]


In [ ]:
# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.84899684, -0.02644833, -2.10512384, ..., -0.87638699,
        0.09687333,  0.67587787])

In [ ]:
#np.zeros()
z= np.zeros(3)
zz = np.zeros((3,4)) #(rows,cols)
print(zz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#np.ones()
o= np.ones(3)
oo = np.ones((3,4)) #(rows,cols)
print(oo)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#random.rand
r = np.random.rand(3,4)
print(r)

[[0.89731252 0.14520751 0.76690087 0.24597562]
 [0.44508146 0.78410968 0.19430219 0.31059256]
 [0.37340449 0.56574282 0.89286512 0.12239681]]


In [ ]:
#random.randint ----> positive random number less than the seeling
r2 = np.random.randint(30,100) # (floor,ceil)
print(r2)
print("---------------------------------\n")
#return a matrix
u = np.random.randint(100,200,(3,4))
print(u)

90
---------------------------------

[[145 183 101 131]
 [123 102 132 143]
 [189 185 103 163]]


In [ ]:
#.reshape()
np_shape = np.random.randint(100,200,10)
shape = np_shape.reshape(5,2) #rows * cols --> = to the number of items
print(np_shape)
print("------------------------------------------\n")
print(shape)

[161 140 187 199 167 147 141 140 121 188]
------------------------------------------

[[161 140]
 [187 199]
 [167 147]
 [141 140]
 [121 188]]


In [ ]:
np_shape2 = np.random.randint(100,200,15)
shape2 = np_shape2.reshape(5,3) #rows, cols --> = to the number of items
print(np_shape2)
print("------------------------------------------\n")
print(shape2)

[116 110 139 129 114 148 141 192 178 109 181 132 170 196 103]
------------------------------------------

[[116 110 139]
 [129 114 148]
 [141 192 178]
 [109 181 132]
 [170 196 103]]


In [ ]:
#shuffle(np_list)
numbers = np.arange(1,10)
print(numbers)
print("------------------------------------------\n")
np.random.shuffle(numbers)
print(numbers)

[1 2 3 4 5 6 7 8 9]
------------------------------------------

[5 1 7 4 8 6 2 9 3]


In [ ]:
numbers2 = np.arange(1,13)
numbers_re = numbers2.reshape(3,4)
print(numbers_re)
print("------------------------------------------\n")
np.random.shuffle(numbers_re)
print(numbers_re)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#max
print(numbers_re.max())
print("------------------------------------------\n")
print(numbers_re.min())
print("------------------------------------------\n")
print(numbers_re.mean())
print("------------------------------------------\n")
print(numbers_re.argmax()) #----> location of the max
print("------------------------------------------\n")
print(numbers_re.argmin()) #----> location of the min

12
------------------------------------------

1
------------------------------------------

6.5
------------------------------------------

11
------------------------------------------

0


In [ ]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

# Get the index of the maximum element in a
print(np.argmax(a))

# Get the index of the minimum element in a
# (this array has two elements with the maximum value -
# only one index is returned)
print(np.argmin(a))

# Get sorted list of indices
print(np.argsort(a))

# Get sorted list of indices in descending order
# [::-1] is a special slicing index that returns the reversed list
print(np.argsort(a)[::-1])

# Get indices of elements that meet some condition
# this returns a tuple, the list of indices is the first entry
# so we use [0] to get it
print(np.where(a > 5)[0])

# Get indices of elements that meet some condition
# this example shows how to get the index of *all* the max values
print(np.where(a >= a[np.argmax(a)])[0])

In [ ]:
#.shape
print(numbers_re.shape)
print(numbers_re.shape[0]) # -----> number of rows
print(numbers_re.shape[1]) # -----> number of cols

(3, 4)
3
4


### let's play with some Maths

In [ ]:
#sorting
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#np.add
add = np.add(3,2)
print(add)
print("------------------------------------------\n")

matrix = [[1,2,3],[4,5,6],[7,8,9]]
madd = np.add(matrix,2) #----> adding a scaler to each element

print(madd)
print("------------------------------------------\n")

mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat2 = [[1,3,4],[4,5,6],[1,2,3]]
mat_add = np.add(mat1,mat2)
print(mat_add)

5
------------------------------------------

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------------------

[[ 2  5  7]
 [ 8 10 12]
 [ 8 10 12]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
#np.ceil
c = np.ceil(2.2)
print(c)

#floor
f = np.floor(2.2)
print(f)

3.0
2.0


In [ ]:
#np.multiply
mul = np.multiply(3,2)
print(mul)
print("------------------------------------------\n")

matrix = [[1,2,3],[4,5,6],[7,8,9]]
mamul = np.add(matrix,2) #----> multipling a scaler to each element
print(mamul)
print("------------------------------------------\n")

mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat2 = [[1,3,4],[4,5,6],[7,8,9]]
mat_mull = np.multiply(mat1,mat2)
# M = A X B
#M2 = B X C
#M3 = A X C
print(mat_mull)

6
------------------------------------------

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------------------------------------------

[[ 1  6 12]
 [16 25 36]
 [49 64 81]]


In [ ]:
#np.divide
div = np.divide(3,2)
print(div)
print("------------------------------------------\n")

matrix = [[1,2,3],[4,5,6],[7,8,9]]
madiv = np.divide(matrix,2) #----> multipling a scaler to each element
print(madiv)
print("------------------------------------------\n")

mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat2 = [[1,3,4],[4,5,6],[7,8,9]]
mat_div = np.divide(mat1,mat2)
print(mat_div)

1.5
------------------------------------------

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
------------------------------------------

[[1.         0.66666667 0.75      ]
 [1.         1.         1.        ]
 [1.         1.         1.        ]]


In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
print("------------------------------------------\n")

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print("------------------------------------------\n")


# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
print("------------------------------------------\n")


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
------------------------------------------

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
------------------------------------------

[[1.         1.41421356]
 [1.73205081 2.        ]]
------------------------------------------



### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"